[package]
name = "parapet"
version = "0.1.0"
authors = ["Dylan McKay <dylanmckay34@gmail.com>"]

description = "Peer to peer build system"
license = "MIT"
repository = "https://github.com/dylanmckay/parapet"

[dependencies]
mio = "0.6"
slab = "0.3.0"
uuid = { version = "0.3.1", features = ["v4", "serde"] }
byteorder = "0.5.3"
graphsearch = "0.6.0"
protocol = { path = "../protocol", features = ["uuid"] }

